export const SET_ARTWORKS = "SET_ARTWORKS"

export const USER_SELECT_RANDOM = "USER_SELECT_RANDOM"

export const USER_SELECT_SEARCH = "USER_SELECT_SEARCH"

export const USER_SELECT_DEPT = "USER_SELECT_DEPT"